ckrobotics_django/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from ckrobotics_django import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ckrobotics_django.views.home', name='home'),
    # url(r'^ckrobotics_django/', include('ckrobotics_django.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^teams/', include('teams.urls', namespace="teams")),
    url(r'^$', views.index, name="index"),
    url(r'^memberhome/', views.memberhome, name="memberhome"),
    url(r'^vex/', views.vex, name="vex"),
    url(r'^logout/', views.logout_view, name="logout"),
    #(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

if not settings.DEBUG:
  urlpatterns += patterns('',
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
  )

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

teams/urls.py
from django.conf.urls import patterns, url

from teams import views

urlpatterns = patterns('',
  # ex: /teams/
  url(r'^$', views.index, name='index'),
  # ex: /teams/5/
  url(r'^(?P<team_id>\d+)/$', views.detail, name='detail'),
)

blog/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from teams.models import Team

class Description(models.Model):
  name = models.CharField(max_length=20)
  text = models.TextField()

class CompetitionGame(models.Model):
	name = models.CharField(max_length=20)
	season_start = models.DateField()
	season_end = models.DateField()
	league = models.ForeignKey(Group)
	current = models.BooleanField()
	description = models.TextField()
	teams = models.TextField()
	rules = models.TextField()

class BlogPost(models.Model):
	title = models.CharField(max_length=50)
	content = models.TextField()
	author = models.ForeignKey(User, blank=True, null=True)
	teamauthor = models.ForeignKey(Team, blank=True, null=True)
	pub_date = models.DateTimeField()

polls/models.py
from django.db import models

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

teams/models.py
from django.db import models
from django.contrib.auth.models import User, Group

class Robot(models.Model):
	name = models.CharField(max_length=50)
	description = models.TextField()

class Member(models.Model):
	def __unicode__(self):
		return self.user.username
	user = models.OneToOneField(User)
	join_date = models.DateField()
	current = models.BooleanField()
	grad_year = models.IntegerField()

class Team(models.Model):
	def __unicode__(self):
		return self.primarygroup.name + ' ' + str(self.number) + ' ' + str(self.name)
	name = models.CharField(max_length=50)
	number = models.IntegerField()
	founded_date = models.DateField()
	members = models.ManyToManyField(Member, blank=True, related_name='teams')
	# league = models.CharField(max_length=1, choices=LEAGUETYPE)
	primarygroup = models.ForeignKey(Group, related_name='primaryteams')
	groups = models.ManyToManyField(Group, related_name='teams')
	robots = models.ManyToManyField(Robot, blank=True)
# Group.add_to_class('team', models.OneToOneField(Team, 
# 	related_name='group', blank=True, null=True))
# Group.team.blank=False
# Group.team.null=False

blog/views.py
# Create your views here.

ckrobotics_django/views.py
from django.http import HttpResponse
from django.http import Http404
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User, Group
from django.shortcuts import render, get_object_or_404
from teams.models import Team
from blog.models import Description
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.contrib.auth import logout

partners = ["Youthville Detroit", "Someone Else",]

def get_data():
	data = {'teams': Team.objects.all(),
						'vex_teams': Team.objects.filter(primarygroup=Group.objects.get(name='VEX')),
						'ftc_teams': Team.objects.filter(primarygroup=Group.objects.get(name='FTC')),
						'fll_teams': Team.objects.filter(primarygroup=Group.objects.get(name='FLL')),
						'vexiq_teams': Team.objects.filter(primarygroup=Group.objects.get(name='VEXIQ')),
						'partners': partners,
					}
	return data

def index(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
				if user.is_active:
					login(request, user)
					return render(request, 'ckrobotics_django/test.html', {'loggedin': True})
				else:
					return render(request, 'ckrobotics_django/test.html', {'loggedin': False})
		else:
			return render(request, 'ckrobotics_django/test.html', {'loggedin': False})
	else:
		data = get_data()
		data.update({
						'title': "CK Robotics",
						'page': 'index',
						})
		return render(request, 'ckrobotics_django/index.html', data)

def vex(request):
	data = get_data()
	data.update({'title': 'About VEX',
					'page': 'vex',
					})
	return render(request, 'ckrobotics_django/vex.html', data);

def logout_view(request):
	logout(request)
	return redirect('/')

@login_required(login_url='/')
def memberhome(request):
	data = get_data()
	data.update({ 'page': 'memberhome',
		})
	return render(request, 'ckrobotics_django/memberhome.html', data)

polls/views.py
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from polls.models import Poll

def index(request):
    latest_poll_list = Poll.objects.all().order_by('-pub_date')[:5]
    context = {'latest_poll_list': latest_poll_list}
    return render(request, 'polls/index.html', context)

def detail(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    return render(request, 'polls/detail.html', {'poll': poll})

def results(request, poll_id):
    return HttpResponse("You're looking at the results of poll %s." % poll_id)

def vote(request, poll_id):
    return HttpResponse("You're voting on poll %s." % poll_id)

teams/views.py
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from teams.models import Team

def index(request):
    #latest_poll_list = Poll.objects.all().order_by('-pub_date')[:5]
    #context = {'latest_poll_list': latest_poll_list}
    context = {'team_list': Team.objects.all()}
    return render(request, 'teams/index.html', context)

def detail(request, team_id):
    team = get_object_or_404(Team, pk=team_id)
    return render(request, 'teams/detail.html', {'team': team})

ckrobotics_django/templates/ckrobotics_django/footer.html
<footer>
        <p>© Cranbrook Kingswood 2013
        </p>
      </footer>

ckrobotics_django/templates/ckrobotics_django/head.html
{% load static %}
<head>
    <meta charset="utf-8">
    <title>{{title}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "css/flat-ui.css" %}" rel="stylesheet">
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <style type="text/css">body {
      padding-top: 30px;
      padding-bottom: 40px;
      }
    </style>
    <!--link(href='/css/bootstrap-responsive.css', rel='stylesheet')-->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static "ico/apple-touch-icon-144-precomposed.png" %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static "ico/apple-touch-icon-114-precomposed.png" %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static "ico/apple-touch-icon-72-precomposed.png" %}">
    <link rel="apple-touch-icon-precomposed" href="{% static "ico/apple-touch-icon-57-precomposed.png" %}">
    <link rel="shortcut icon" href="{% static "ico/favicon.ico" %}">
</head>

ckrobotics_django/templates/ckrobotics_django/homepage-hero.html
<div class="hero-unit">
        <h1>Welcome to CK Robotics!
        </h1>
        <p>Cranbrook Robotics is a robotics group for all levels of skill in suburban Detroit. This group aims to give its members chances to experience life as engineers using STEM (science, technology engineering math)
        </p>
        <p><a class="btn btn-primary btn-large">Learn more »</a>
        </p>
      </div>

ckrobotics_django/templates/ckrobotics_django/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  {% include "ckrobotics_django/head.html" %}
  <body>
    {% include "ckrobotics_django/preheader.html" %}
    <div class="container main">
      {% include "ckrobotics_django/navbar.html" %}  
      {% include "ckrobotics_django/homepage-hero.html" %}  
      {% include "ckrobotics_django/infofooter.html" %}
      {% include "ckrobotics_django/footer.html" %}
    </div>
  </body>
  {% include "ckrobotics_django/scripts.html" %}
</html>

ckrobotics_django/templates/ckrobotics_django/infofooter.html
{% load static %}
<div class="row">
  <div class="span4">
    <img class="tile-image pull-center" alt="" src="{% static "img/first.png" %}"/>
    <p align="justify" >First is an international competition where students of all ages create robots to overcome an obstacle or challenge. First allows our students to work with professional engineers to enhance their experience. At Cranbrook we aim to provide the programs first delivers, so our club hosts multiple FLL teams as well as FTC teams.
    </p>
    <p><a class="btn" href="#">View details »</a>
    </p>
  </div>
  <div class="span4">
    <img class="tile-image pull-center" alt="" src="{% static "img/cklogo.png" %}" height="92"/>
    <p align="justify" >Cranbrook robotics club is a group of students from Cranbrook Kingswood Schools. A Cranbrook school is a prestigious preparatory boarding school in Bloomfield Hills, Michigan with distinguished alumni ranging from the runner up to the 2012 presidential election, Mitt Romney to small business owners.
    </p>
    <a class="btn" href="#" >View details »</a>
  </div>
  <div class="span4">
    <img class="tile-image pull-center" alt="" src="{% static "img/vex.gif" %}"/>
    <p align="justify" >VRC is another international competition that branches off of First, but it allows for cheaper, more accessible, and standardized products. At Cranbrook we run many VEX teams in the high school and middle school, but we will also be taking advantage of the latest VEX IQ and running elementary school teams as well.
    </p>
    <p><a class="btn" href="#">View details »</a>
    </p>
  </div>
</div>

ckrobotics_django/templates/ckrobotics_django/member-navbar.html
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container"><a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li {% if page == 'memberhome' %} class="active" {% endif %}><a href="/memberhome">Member Home</a>
          </li>
          <li><a href="#">My Teams</a>
            <ul>
              {% for team in request.user.member.teams.all %}
                <li {% if page == team.name %} class="active" {% endif %} ><a href="#">{{ team.name }}</a></li>
              {% endfor %}
            </ul>
          </li>
        </ul>
        <ul class="nav pull-right">
          <li><a href="/">Home</a>
          </li>
          <li><a href="/logout">Sign Out</a>
          </li>
        </ul>
      </div>
      </div>
  </div>
</div>

ckrobotics_django/templates/ckrobotics_django/memberhome.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  {% include "ckrobotics_django/head.html" %}
  <body>
    {% include "ckrobotics_django/preheader.html" %}
    <div class="container main">
    	{% include "ckrobotics_django/member-navbar.html" %}
    </div>
  </body>
  {% include "ckrobotics_django/scripts.html" %}
</html>

ckrobotics_django/templates/ckrobotics_django/navbar.html
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container"><a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li {% if page == 'index' %} class="active" {% endif %}><a href="/">Home</a>
          </li>
          <li {% if page == 'news' %} class="active" {% endif %}><a href="#news">News</a>
          </li>
          <li {% if page == 'about' %} class="active" {% endif %}><a href="#about">About</a>
          </li>
          <li {% if page == 'vex' %} class="active" {% endif %}><a href="/vex">VEX</a>
            <ul>
              {% for team in vex_teams %}
                <li {% if page == team.name %} class="active" {% endif %} ><a href="#">{{ team.name }}</a></li>
              {% endfor %}
            </ul>
          </li>
          <li {% if page == 'vexiq' %} class="active" {% endif %}><a href="/vexiq">VEXIQ</a>
            <ul>
              {% for team in vexiq_teams %}
                <li {% if page == team.name %} class="active" {% endif %} ><a href="#">{{ team.name }}</a></li>
              {% endfor %}
            </ul>
          </li>
          <li {% if page == 'ftc' %} class="active" {% endif %}><a href="/ftc">FTC</a>
            <ul>
              {% for team in ftc_teams %}
                <li {% if page == team.name %} class="active" {% endif %} ><a href="#">{{ team.name }}</a></li>
              {% endfor %}
            </ul>
          </li>
          <li {% if page == 'fll' %} class="active" {% endif %}><a href="/fll">FLL</a>
            <ul>
              {% for team in fll_teams %}
                <li {% if page == team.name %} class="active" {% endif %} ><a href="#">{{ team.name }}</a></li>
              {% endfor %}
            </ul>
          </li>
          </ul>
        <ul class="nav pull-right">
          {% if request.user.is_authenticated %}
            <li><a href="/memberhome">Member Home</a>
          {% else %}
          <li><a href="#">Sign In</a>
            <ul class="login-list">
              <li>
                <div class="login-form">
                  <form id='login' method='post'>
                    {% csrf_token %}
                    <div class="control-group">
                      <input name="username" class="input login-field" type="text" placeholder="Email address"/>
                      <label class="login-field-icon fui-man-16" for="login-name"></label>
                    </div>
                    <div class="control-group">
                      <input name="password" class="input login-field" type="password" placeholder="Password"/>
                      <label class="login-field-icon fui-lock-16" for="login-pass"></label>
                    </div>
                    <div class="pull-right">
                      <label class="checkbox rememberme">
                        <input class="palette" type="checkbox" value="remember-me">Remember</label>
                    </div>
                    <button class="btn btn-large btn-primary" type="submit" value="Submit">Sign In
                    </button>
                </form>
              </ul>
            </li>
          {% endif %}
          </li>
        </ul>
      </div>
      </div>
  </div>
</div>

ckrobotics_django/templates/ckrobotics_django/preheader.html
<div class="preheader">
  <div class="container"><a href="/">
      <!--img(src="/img/logo_arc_blue.jpg", alt="Cranbrook Robotics")--></a>
  </div>
</div>

ckrobotics_django/templates/ckrobotics_django/scripts.html
{% load static %}
<!-- Load JS here for greater good =============================-->
<script src="{% static "js/jquery-1.8.2.min.js" %}"></script>
<script src="{% static "js/jquery-ui-1.10.0.custom.min.js" %}"></script>
<script src="{% static "js/jquery.dropkick-1.0.0.js" %}"></script>
<script src="{% static "js/custom_checkbox_and_radio.js" %}"></script>
<script src="{% static "js/custom_radio.js" %}"></script>
<script src="{% static "js/jquery.tagsinput.js" %}"></script>
<script src="{% static "js/bootstrap-tooltip.js" %}"></script>
<script src="{% static "js/jquery.placeholder.js" %}"></script>
<script src="{% static "//vjs.zencdn.net/c/video.js" %}"></script>
<script src="{% static "js/application.js" %}"></script>
<script src="{% static "js/bootstrap.js" %}"></script>

ckrobotics_django/templates/ckrobotics_django/test.html
{{ loggedin }}

ckrobotics_django/templates/ckrobotics_django/vex.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  {% include "ckrobotics_django/head.html" %}
  <body data-spy="scroll" data-target=".vex-sidebar">
    {% include "ckrobotics_django/preheader.html" %}
    <div class="container main">
      {% include "ckrobotics_django/navbar.html" %}
      <div class="row">
	      <div class="span3 vex-sidebar">
	        <ul class="nav nav-list vex-sidenav" data-spy="affix" data-offset-top="220">
	          <li><a href="#tossup"><i class="icon-chevron-right"></i>Toss Up</a></li>
	          <li><a href="#sackattack"><i class="icon-chevron-right"></i>Sack Attack</a></li>
	          <li><a href="#gateway"><i class="icon-chevron-right"></i>Gateway</a></li>
	          <li><a href="#roundup"><i class="icon-chevron-right"></i>Round Up</a></li>
	          <li><a href="#cleansweep"><i class="icon-chevron-right"></i>Clean Sweep</a></li>
	          <li><a href="#elevation"><i class="icon-chevron-right"></i>Elevation</a></li>
	        </ul>
	      </div>
	      <div class="span9">
	      	<section id="tossup">
	      		<div class="page-header">
	            <h1>Toss Up</h1>
	          </div>
	          <iframe class="pull-center youtube" width="560" height="315" src="http://www.youtube.com/embed/3euUzfn0TwI" frameborder="0" allowfullscreen></iframe>
			      <p class="lead">
			      	The object of the game is to attain a higher score than the opposing Alliance by Scoring your colored BuckyBalls and Large Balls into the Middle Zone and Goal Zone, by Stashing your colored BuckyBalls and Large Balls into the Goals, and by Hanging or Hanging With A Ball, at various heights, off your colored Bar at the end of the match. There are a total of twenty (20) BuckyBalls and eight (8) Large Balls available as Scoring Objects in the game. Most Scoring Objects begin in designated locations on the field, while some are available to be loaded prior to the Match.
			      </p>
	          <div class="row-fluid">
	            <div class="span6">
	              <h2>Teams</h2>
	              <p>VEX Toss Up is played on a 12’x12’ square field configured as seen above. Two alliances – one “red” and one “blue” – composed of two teams each, compete in matches consisting of a fifteen second autonomous period followed by one minute and forty-five seconds of driver-controlled play.</p>
	            </div>
	            <div class="span6">
	              <h2>Rules</h2>
	              <p>Each Robot (smaller than 18”x18”x18” to start) begins a match on one of their Alliance Starting Tiles. There are two (2) scoring Zones and (2) Goals that Alliances can Score Objects into. Alliances also earn points for having Robots of their own color Hanging from their Hanging Bar at the end of the Match. A bonus is awarded to the Alliance that has the most total points at the end of the Autonomous Period.</p>
	            </div>
	          </div>
	        </section>
	        <section id="sackattack">
	      		<div class="page-header">
	            <h1>Sack Attack</h1>
	          </div>
	          <iframe class="pull-center youtube" width="420" height="315" src="http://www.youtube.com/embed/N-ehrKSYfjk" frameborder="0" allowfullscreen></iframe>
			      <p class="lead">
			      	The object of the game is to attain a higher score than the opposing Alliance by Scoring Sacks and Bonus Sacks in your colored Floor Goals, Troughs and High Goal, and by having the most Robots of your color Parked at the end of the Match.
			      </p>
	          <div class="row-fluid">
	            <div class="span6">
	              <h2>Teams</h2>
	              <p>VEX Sack Attack is played on a 12’x12’ square field configured as seen above. Two alliances – one “red” and one “blue” – composed of two teams each, compete in matches consisting of a fifteen second autonomous period followed by one minute and forty-five seconds of driver- controlled play.
	              </p>
	            </div>
	            <div class="span6">
	              <h2>Rules</h2>
	              <p>There are a total of ninety-eight (98) Sacks and four (4) Bonus Sacks available as Scoring Objects in the game. Most Scoring Objects begin in designated locations on the field, while some are available to be loaded prior or during the Match. Each Robot (smaller than 18”x18”x18” to start) begins a match on one of their Alliance Starting Tiles. There are ten (10) scoring areas, five (5) of each color, of varying heights which teams can Score Sacks or Bonus Sacks in. Alliances earn a bonus for having the most Robots of their own color touching their Alliance Starting Tiles at the end of the Match. A bonus is awarded to the Alliance that has the most total points at the end of the Autonomous Period.</p>
	            </div>
	          </div>
	        </section>
	        <section id="gateway">
	      		<div class="page-header">
	            <h1>Gateway</h1>
	          </div>
	          <iframe class="pull-center youtube" width="420" height="315" src="http://www.youtube.com/embed/N-ehrKSYfjk" frameborder="0" allowfullscreen></iframe>
			      <p class="lead">
			      	The object of the game is to attain a higher score than the opposing Alliance by Scoring Sacks and Bonus Sacks in your colored Floor Goals, Troughs and High Goal, and by having the most Robots of your color Parked at the end of the Match.
			      </p>
	          <div class="row-fluid">
	            <div class="span6">
	              <h2>Teams</h2>
	              <p>VEX Sack Attack is played on a 12’x12’ square field configured as seen above. Two alliances – one “red” and one “blue” – composed of two teams each, compete in matches consisting of a fifteen second autonomous period followed by one minute and forty-five seconds of driver- controlled play.
	              </p>
	            </div>
	            <div class="span6">
	              <h2>Rules</h2>
	              <p>There are a total of ninety-eight (98) Sacks and four (4) Bonus Sacks available as Scoring Objects in the game. Most Scoring Objects begin in designated locations on the field, while some are available to be loaded prior or during the Match. Each Robot (smaller than 18”x18”x18” to start) begins a match on one of their Alliance Starting Tiles. There are ten (10) scoring areas, five (5) of each color, of varying heights which teams can Score Sacks or Bonus Sacks in. Alliances earn a bonus for having the most Robots of their own color touching their Alliance Starting Tiles at the end of the Match. A bonus is awarded to the Alliance that has the most total points at the end of the Autonomous Period.</p>
	            </div>
	          </div>
	        </section>
	        <section id="roundup">
	      		<div class="page-header">
	            <h1>Round Up</h1>
	          </div>
	          <iframe class="pull-center youtube" width="420" height="315" src="http://www.youtube.com/embed/N-ehrKSYfjk" frameborder="0" allowfullscreen></iframe>
			      <p class="lead">
			      	The object of the game is to attain a higher score than the opposing Alliance by Scoring Sacks and Bonus Sacks in your colored Floor Goals, Troughs and High Goal, and by having the most Robots of your color Parked at the end of the Match.
			      </p>
	          <div class="row-fluid">
	            <div class="span6">
	              <h2>Teams</h2>
	              <p>VEX Sack Attack is played on a 12’x12’ square field configured as seen above. Two alliances – one “red” and one “blue” – composed of two teams each, compete in matches consisting of a fifteen second autonomous period followed by one minute and forty-five seconds of driver- controlled play.
	              </p>
	            </div>
	            <div class="span6">
	              <h2>Rules</h2>
	              <p>There are a total of ninety-eight (98) Sacks and four (4) Bonus Sacks available as Scoring Objects in the game. Most Scoring Objects begin in designated locations on the field, while some are available to be loaded prior or during the Match. Each Robot (smaller than 18”x18”x18” to start) begins a match on one of their Alliance Starting Tiles. There are ten (10) scoring areas, five (5) of each color, of varying heights which teams can Score Sacks or Bonus Sacks in. Alliances earn a bonus for having the most Robots of their own color touching their Alliance Starting Tiles at the end of the Match. A bonus is awarded to the Alliance that has the most total points at the end of the Autonomous Period.</p>
	            </div>
	          </div>
	        </section>
	        <section id="cleansweep">
	      		<div class="page-header">
	            <h1>Clean Sweep</h1>
	          </div>
	          <iframe class="pull-center youtube" width="420" height="315" src="http://www.youtube.com/embed/N-ehrKSYfjk" frameborder="0" allowfullscreen></iframe>
			      <p class="lead">
			      	The object of the game is to attain a higher score than the opposing Alliance by Scoring Sacks and Bonus Sacks in your colored Floor Goals, Troughs and High Goal, and by having the most Robots of your color Parked at the end of the Match.
			      </p>
	          <div class="row-fluid">
	            <div class="span6">
	              <h2>Teams</h2>
	              <p>VEX Sack Attack is played on a 12’x12’ square field configured as seen above. Two alliances – one “red” and one “blue” – composed of two teams each, compete in matches consisting of a fifteen second autonomous period followed by one minute and forty-five seconds of driver- controlled play.
	              </p>
	            </div>
	            <div class="span6">
	              <h2>Rules</h2>
	              <p>There are a total of ninety-eight (98) Sacks and four (4) Bonus Sacks available as Scoring Objects in the game. Most Scoring Objects begin in designated locations on the field, while some are available to be loaded prior or during the Match. Each Robot (smaller than 18”x18”x18” to start) begins a match on one of their Alliance Starting Tiles. There are ten (10) scoring areas, five (5) of each color, of varying heights which teams can Score Sacks or Bonus Sacks in. Alliances earn a bonus for having the most Robots of their own color touching their Alliance Starting Tiles at the end of the Match. A bonus is awarded to the Alliance that has the most total points at the end of the Autonomous Period.</p>
	            </div>
	          </div>
	        </section>
	        <section id="elevation">
	      		<div class="page-header">
	            <h1>Elevation</h1>
	          </div>
	          <iframe class="pull-center youtube" width="420" height="315" src="http://www.youtube.com/embed/N-ehrKSYfjk" frameborder="0" allowfullscreen></iframe>
			      <p class="lead">
			      	The object of the game is to attain a higher score than the opposing Alliance by Scoring Sacks and Bonus Sacks in your colored Floor Goals, Troughs and High Goal, and by having the most Robots of your color Parked at the end of the Match.
			      </p>
	          <div class="row-fluid">
	            <div class="span6">
	              <h2>Teams</h2>
	              <p>VEX Sack Attack is played on a 12’x12’ square field configured as seen above. Two alliances – one “red” and one “blue” – composed of two teams each, compete in matches consisting of a fifteen second autonomous period followed by one minute and forty-five seconds of driver- controlled play.
	              </p>
	            </div>
	            <div class="span6">
	              <h2>Rules</h2>
	              <p>There are a total of ninety-eight (98) Sacks and four (4) Bonus Sacks available as Scoring Objects in the game. Most Scoring Objects begin in designated locations on the field, while some are available to be loaded prior or during the Match. Each Robot (smaller than 18”x18”x18” to start) begins a match on one of their Alliance Starting Tiles. There are ten (10) scoring areas, five (5) of each color, of varying heights which teams can Score Sacks or Bonus Sacks in. Alliances earn a bonus for having the most Robots of their own color touching their Alliance Starting Tiles at the end of the Match. A bonus is awarded to the Alliance that has the most total points at the end of the Autonomous Period.</p>
	            </div>
	          </div>
	        </section>
		    </div>
	    </div>
	  </div>
  </body>
  {% include "ckrobotics_django/scripts.html" %}
</html>

polls/templates/polls/detail.html
<h1>{{ poll.question }}</h1>
<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

polls/templates/polls/index.html
{% if latest_poll_list %}
    <ul>
    {% for poll in latest_poll_list %}
        <li><a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}